[#419] Page nav footer
Hexlet/hexletguides.github.io pull request #427
Opened 2022-08-23 14:41 UTC by hellion86

2022-08-23 15:50 UTC, seth2810 commented on next-app/api/index.js
> +  const numOfposts = posts.length - 1;
```suggestion
  const postsCount = posts.length - 1;
```

2022-08-23 15:50 UTC, seth2810 commented on next-app/api/index.js
>    const post = posts.find((post) => post.name === name);
```suggestion
  const postIndex = posts.findIndex((post) => post.name === name);
```

2022-08-23 15:51 UTC, seth2810 commented on next-app/api/index.js
> +  const nextPost = postIndex === numOfposts ? posts[0] : posts[postIndex + 1];
Эти проверки имеет смысл перенести ниже условия когда пост не найден.

2022-08-23 15:56 UTC, seth2810 commented on next-app/components/PostPageNav.jsx
> +          <Link href={prevLink.name}>
```suggestion
          const prevHref = {
              pathname: '/[name]',
              query: {
                  name: prevLink.name,
              },
          };
          <Link href={prevHref}>
```

Так next.js будет строить ссылки в соответствии с текущей локалью - https://nextjs.org/docs/api-reference/next/link#with-url-object

2022-08-23 15:57 UTC, seth2810 commented on next-app/components/PostPageNav.jsx
> +const PostPageNav = ({ nextLink, prevLink }) => {
```suggestion
const PostPageNav = ({ nextPost, prevPost }) => {
```

2022-08-23 15:58 UTC, seth2810 commented
@fey, @ashikov заапрувьте пайплайн 🙏🏾

2022-08-24 15:17 UTC, hellion86 commented on next-app/components/PostPageNav.jsx
> +const PostPageNav = ({ nextLink, prevLink }) => {
я надеюсь правильно понял идею, отдавать не то что требуется в компоненте, а прям весь пост сразу

2022-08-24 15:17 UTC, hellion86 commented on next-app/api/index.js
>    const post = posts.find((post) => post.name === name);
поправил

2022-08-24 15:18 UTC, hellion86 commented on next-app/components/PostPageNav.jsx
> +          <Link href={prevLink.name}>
не знал про этот момент, я сначала подумал что нужно как то формировать ссылки с учетом языка - но оно работало и так :)

2022-08-25 09:27 UTC, seth2810 commented on next-app/components/PostPageNav.jsx
> +const PostPageNav = ({ nextLink, prevLink }) => {
структуру объектов можно оставить прежней, здесь я больше хотел через нейминг подчеркнуть, что объекты больше описывают данные постов, а не ссылок на них.

2022-08-25 09:30 UTC, seth2810 commented on next-app/components/PostPageNav.jsx
> +const PostPageNav = ({ nextLink, prevLink }) => {
если передавать весь пост, то это скажется на том, что между сервером и клиентом будет еще дополнительно ходить информация с содержимым поста (content) и др. свойствами, которая в дальнейшем не будет использоваться.

2022-08-25 09:54 UTC, seth2810 requested changes

2022-08-25 09:54 UTC, seth2810 commented on next-app/components/PostPageNav.jsx
> +  const makeHref = (link) => ({
```suggestion
  const makePostHref = (name) => ({
```

2022-08-25 09:54 UTC, seth2810 commented on next-app/data/posts/en/2022-06-10-makefile-as-task-runner.md
> +target1: # target name, you can also use kebab-case or snake_case
поправь пожалуйста точно такую же опечатку [здесь](https://github.com/Hexlet/hexletguides.github.io/blob/main/_i18n/en/_posts/2022-06-10-makefile-as-task-runner.md?plain=1#L58)

2022-08-25 09:54 UTC, seth2810 commented on next-app/components/PostPageNav.jsx
> +  const makeHref = (link) => ({
+ возможно имеет смысл вынести определение функции на уровень модуля, чтобы не создавать ее каждый раз внутри тела компонента?

2022-08-25 09:54 UTC, seth2810 commented on next-app/api/index.js
> +    nextPost,
здесь все же предлагаю ограничиться только полезной информацией, либо доставать ее на уровне выше в `getStaticProps`

2022-08-25 12:54 UTC, hellion86 commented on next-app/data/posts/en/2022-06-10-makefile-as-task-runner.md
> +target1: # target name, you can also use kebab-case or snake_case
ok

2022-08-25 12:56 UTC, hellion86 commented on next-app/api/index.js
> +    nextPost,
Оставил в findPost. Попробовал сделать и в getStaticProps - но там все равно придется делать проход по постам для поиска индекса нужного поста и определения его соседей. С другой стороны, findPost должен заниматься только поиском конкретного поста, а не всего сразу.

2022-08-26 08:49 UTC, seth2810 approved these changes

2022-08-26 09:17 UTC, merged