#365 created page with xml(rss)
Hexlet/hexletguides.github.io pull request #432
Opened 2022-09-04 10:51 UTC by Aleksandr-Bondarev

2022-09-05 13:02 UTC, seth2810 requested changes

2022-09-05 13:02 UTC, seth2810 commented on next-app/pages/feed.xml.js
> +                <link>http://localhost:3000/makefile-as-task-runner/</link>
@Aleksandr-Bondarev кажется так не пойдет. Предлагаю глянуть [сюда](https://dev.to/j471n/how-to-add-rss-feed-in-nextjs-blog-34j1)

2022-09-12 06:07 UTC, Aleksandr-Bondarev commented on next-app/pages/feed.xml.js
> +                <link>http://localhost:3000/makefile-as-task-runner/</link>
Забыл отписаться, сделал генерацию по примеру из статьи, валидный rss отдаётся по роуту /feed.xml, проверял с помощью RSS Feed Reader

2022-09-12 21:23 UTC, seth2810 requested changes

2022-09-12 21:23 UTC, seth2810 commented on next-app/api/index.js
> +  fs.writeFileSync("./public/feed.xml", feed.rss2());
```suggestion
  return fsp.writeFile("./public/feed.xml", feed.rss2());
```

2022-09-12 21:23 UTC, seth2810 commented on next-app/api/index.js
> +      // image: post.image,
Не используемый код лучше удалить

2022-09-12 21:23 UTC, seth2810 commented on next-app/api/index.js
> +    title: "Hexlet Guides",
Такие параметры лучше брать из конфига

2022-09-12 21:23 UTC, seth2810 commented on next-app/api/index.js
> +  const siteURL = 'http://localhost:3000';
Кажется так быть не должно - https://github.com/Hexlet/hexletguides.github.io/blob/gh-pages/feed.xml#L8:

```
<link>https://guides.hexlet.io/</link>
```

2022-09-12 21:23 UTC, seth2810 commented on next-app/api/index.js
> +      // image: post.image,
Еще кажется, что дата публикации все же должна быть:

```
<pubDate>Fri, 10 Jun 2022 00:00:00 +0000</pubDate>
```

2022-09-12 21:23 UTC, seth2810 commented on next-app/pages/index.js
> +    ...await generateRssFeed(locale),
Есть ощущение, что генерация должна выполняться не здесь, а в отдельной команде перед деплоем (см. как сделан sitemap)

2022-09-14 20:32 UTC, Aleksandr-Bondarev commented on next-app/api/index.js
> +      // image: post.image,
Пост не содержит информацию о дате публикации. В каждом файле есть ключи title, subtitle, description, image и author. Или дату можно получить как-то ещё?

2022-09-16 12:51 UTC, seth2810 commented
@Aleksandr-Bondarev поправишь?

2022-09-17 19:21 UTC, Aleksandr-Bondarev commented on next-app/pages/index.js
> +    ...await generateRssFeed(locale),
@seth2810 Привет, я попытался сделать пребилд скрипт “prebuild”: “node <СКРИПТ>”, но так как в package.json не указан “type”:”module”, команда падает с ошибкой. Так как в скрипте используется код, который выполняется в рамках рантайма next.js, все функции (с зависимостями) переписать на CommonJS модули тоже не вышло. Попытки использовать расширение .mjs и флаги типа —experimental-modules так же не привели к успеху. Пожалуйста, подскажи, как можно решить эту проблему

2022-09-17 19:29 UTC, Aleksandr-Bondarev commented on next-app/pages/index.js
> +    ...await generateRssFeed(locale),
@seth2810 Привет, я попытался сделать пребилд скрипт (“prebuild”: “node <путь к скрипту>”), но так как в package.json не указан “type”: ”module”, команда падает с ошибкой. Так как в скрипте используется код, который выполняется в рамках рантайма next.js, все функции (с зависимостями) переписать на CommonJS модули тоже не вышло. Попытки использовать расширение .mjs и флаги типа —experimental-modules так же не привели к успеху. Пожалуйста, подскажи, как можно решить эту проблему

2022-09-18 19:17 UTC, seth2810 commented on next-app/pages/index.js
> +    ...await generateRssFeed(locale),
@Aleksandr-Bondarev предлагаю тебе запушить свой код, пусть и не рабочий, чтобы я мог смотреть предметно 😉

2022-09-18 21:26 UTC, seth2810 commented on next-app/pages/index.js
> +    ...await generateRssFeed(locale),
@Aleksandr-Bondarev учитывая, что будет необходимо генерировать фиды под разные локали, нашел другой способ позволяющий это сделать более привычным для next.js путем. Завтра пришлю PR в твой репозиторий с правками. Так же переделаем заодно генерацию sitemap's, чтобы было единообразно 🤝

2022-09-23 10:54 UTC, seth2810 commented
Перенес изменения вместе со своими правками в #448 

@Aleksandr-Bondarev можешь закрыть PR плз.

2022-09-23 11:35 UTC, closed without merging