correct grammar in 3 guides
Hexlet/hexletguides.github.io pull request #450
Opened 2022-10-09 08:24 UTC by evgeniyworkbel

2022-10-09 13:55 UTC, ashikov commented
@nikafilimonova глянь, плиз

2022-10-12 21:04 UTC, dorjechang commented
Этот PR не столько исправляет ошибки, сколько вносит их. И довольно грубые порой.

- Первая правка: здесь нет грамматической ошибки. И стилистической тоже нет.
- Вторая правка: Наречное выражение “В таком случае” практически никогда не выделяется запятыми. Замена запятой на тире — ошибка, в выражении есть неявное “то”.
- Третья правка: грубейшая ошибка, здесь нельзя ставить запятую.
- Четвёртая правка: ошибки нет. Вопрос вкуса/стиля.
- Пятая правка: не следует злоупотреблять скобками с целью внесения пояснений, определений, примечаний к тексту. В данном случае следовало бы использовать тире.
- Шестая правка: множественное перечисление, запятые использованы правильно. “Один, или три, или пять”, а не “Один или три, или пять”.
- Седьмая правка: оба варианта — и исходный, и правка — плохи. В исходном запятую необходимо поставить не перед “потому”, а после. Замена на “т.к.” — мерзкий канцелярит.

Дальше уже не разбираю, семи замечаний и так достаточно для отклонения PR.

2022-10-13 08:56 UTC, evgeniyworkbel commented
1. дан пример, в котором перечисляются действия. Будет понятнее, если разделить одно предложение на два.
2. согласен
3. деепричастный оборот и его всегда следует выделять запятой. Ошибка как раз-таки не выделять его
4. причина-следствие. Мой вариант будет грамотнее, т.к. выражает это, а исходный нет
5. злоупотребление скобками - это когда они ставятся несколько раз в одном предложении. Опять же: мой вариант семантически выражает верно и для читателя понятнее
6. не нашел про то, что вы пишете ("Шестая правка: множественное перечисление, запятые использованы правильно. “Один, или три, или пять”, а не “Один или три, или пять”.")
7. в корне неверно. Ставить запятую после "потому" - это грубейшая ошибка. Запятая перед союзом "потому что" ставится ПЕРЕД, а не в середине. Если "т.к." канцелярит, то "потому что" - такой же канцелярит, но понятнее будет в данном случае с "т.к.".

Прошу пересмотреть свое решение и проверить все мои правки

2022-10-13 12:50 UTC, dorjechang commented
1. Про “будет понятнее” следовало бы уточнить у читателей прежде, чем утверждать “Будет понятнее”.
2. .
3. Всегда? Не следует позволять себе безапелляционные утверждения, особенно в контексте столь сложных тем, как русский язык. Деепричастный оборот далеко не всегда выделяется запятыми. Например, если он тесно связан с глаголом-сказуемым. Прямо как в нашем случае, “запускать не выходя”, или в последней из предложенных правок “делает благодаря”. Будь этот оборот хоть трижды деепричастным — никаких запятых.
4. Могу лишь повториться — ошибки в исходном варианте нет. Он ничуть не менее грамотный, как и предложенная правка. С “будет грамотнее” я не стану ни спорить, ни соглашаться, потому и сказал — вопрос вкуса/стиля. А Дитмар Ильяшевич давно покинул нас, увы.
5. В хорошем — грамотном и понятном — повествовании вообще не должно быть скобок. Хотя бы потому, что они, мягко говоря, сложно интонируются. Обсуждаемый текст — чистой воды повествование. А про “для читателя понятнее” я уже в п.1 высказался.
6. Внимательнее надо, коллега. “Кто-то переустановит SSH-сервер, или всю ОС, или вообще компьютер”. Не надо удалять запятую после “SSH-сервер”.
7. И опять абсолютистское утверждение. Про запятую после “потому”. Лев Николаевич не знал? И поэтому в “Анне Карениной” использовал оборот “потому, что” более ста раз? Что мы хотим акцентировать в предложении — событие или причину? “Вы об этом узнаете потому, что изменился отпечаток”. Здесь бессмысленно акцентировать перспективное событие, оно произойдёт в любом случае. А акцентировать причину грядущего как раз важно, “Предупреждён — вооружён”. А в этом случае — как и ещё в очень многих случаях — пишется “потому, что”. И интонируется тоже, кстати.

2022-10-14 05:53 UTC, ashikov commented
@NatalieKonstantinova тут нужна помощь редакторов :)

2022-10-14 08:32 UTC, evgeniyworkbel commented
@dorjechang,
1. так я являюсь читателем, перешел на статью из курса и прочел ее. Вы пишете, что логическая связь разрывается - это лишь ваше мнение. Здесь связь не разрывается.
2. поправлю
3. [Правила русской орфографии и пунктуации](https://docs.cntd.ru/document/456059840), глава "Запятые при обстоятельственных оборотах". Открываем, читаем.
Цитирую "Деепричастия, как с пояснительными словами, так и без них, кроме таких одиночных деепричастий и деепричастных оборотов, которые примыкают непосредственно к сказуемому и по своему значению приближаются к наречию". 
Ниже примеры к правилу. Обратите внимание на примеры про тесносвязанность глагола и деепричастия. "Тесно связан" означает, что деепричастие находится рядом с глаголом и образует единое смысловое значение. Пару примеров из Правил: "Вы и в залу входите танцуя", "До двух часов занятия должны были идти не прерываясь", "Он сидит наклонившись и слушает"

А теперь смотрим предложение из гайда "Вам нужен способ запускать команды на этом компьютере не выходя из своего дома". Посмотрите позицию глагола и деепричастного оборота. 
Ч.т.д.
4. в исходном варианте союз "и" не выражает причинно-следственную связь, поэтому его следует изменить.
5. не нравятся скобки - можно заменить на тире. Но исходный вариант точно следует исправить. Могу поправить на тире
6. Подозреваю, что кроме моей правки там нужно еще и удалять запятую после слова "компьютер". Но не буду утверждать в целом насчет этого предложения, т.к. оно построено сложно и на 100% я не уверен. 
7. не сравнивайте пожалуйста гайды с художественной литературой, особенно с Анной Карениной, Война и Мир, и т.п. Это путь к внесению осмысленных ошибок в учебные текста на Хекслете.
А теперь к сути вопроса: читаем Правила русской орфографии и пунктуации (ссылку давал выше). 
Цитирую "Когда придаточное предложение стоит после главного, запятая при сложных подчинительных союзах (потому что, ввиду того что, благодаря тому что и т.п.), как и при простых союзах, ставится один раз - перед союзом, например:
"Глупцы и люди ограниченные всему верят, потому что не могут ничего исследовать.""

Спасибо за ревью, но жду профессионального мнения от другого человека.

2022-10-14 14:47 UTC, evgeniyworkbel commented
@nicha3381 я могу переделать и отправить повторный PR?

2022-10-14 15:42 UTC, ashikov commented
Можно просто добавить коммиты в эту ветку и запушить. Они попадут в данный пуллреквест.

2022-10-14 20:17 UTC, evgeniyworkbel commented
@ashikov @nicha3381 учёл замечания, привел в соответствие и запушил новый коммит

2022-10-18 12:44 UTC, evgeniyworkbel commented
а как правильно будет дальше продолжать работать в этой ветке? Допустим, я откорректирую новые гайды. После пуша коммиты появятся ведь в этом PR

2022-10-19 03:15 UTC, ashikov commented
После того как пуллреквест будет влит и закрыт, можно будет обновить локальную ветку и продолжать с ней работать. Ну и новый PR потом создать, если понадобится.

2022-10-19 11:51 UTC, evgeniyworkbel commented
ок, тогда жду закрытия этого PR и мержа

2022-10-24 10:15 UTC, Malcom1986 requested changes

2022-10-24 10:15 UTC, Malcom1986 commented on _i18n/ru/_posts/2017-07-10-ssh.md
> +Представим, что вы подключились к удаленному серверу **X**. Дальше вы хотите подключиться с него к другому серверу **Y** — например, чтобы сделать `git pull` с GitHub. Вэтом случае придется держать к
В этом случае - нужен пробел

2022-10-24 10:15 UTC, Malcom1986 commented on _i18n/ru/_posts/2020-06-27-webpack.md
> +В теории, код можно писать и без использования системы модулей, но этот способ невероятно трудозатратный и основывается на том, что все определения в коде глобальны (а значит, можно легко что-нибудь
причем - Букву Ё не используем

2022-10-24 12:24 UTC, Malcom1986 commented
Евгений, а у вас ветка correct-guides отслеживает одноименную на удаленном репозитории? Попробуйте запушить с указанием удаленного репозитория и ветки: git push origin correct-guides

2022-10-24 18:16 UTC, dzencot commented
Сейчас осущевствляется переезд на next.js. Попробуйте заново установить. Плюс сейчас немного поменяется путь к постам. Можете плз внести правки уже после изменений?

2022-10-24 21:20 UTC, evgeniyworkbel commented
> Евгений, а у вас ветка correct-guides отслеживает одноименную на удаленном репозитории? Попробуйте запушить с указанием удаленного репозитория и ветки: git push origin correct-guides

пробовал, тоже самое

2022-10-24 21:21 UTC, evgeniyworkbel commented
> Сейчас осущевствляется переезд на next.js. Попробуйте заново установить. Плюс сейчас немного поменяется путь к постам. Можете плз внести правки уже после изменений?

без проблем. Сколько переезд займет по времени?

2022-10-25 13:52 UTC, dzencot commented
https://github.com/Hexlet/hexletguides.github.io/pull/523 - после этого пр можно мержить

2022-10-27 08:06 UTC, evgeniyworkbel commented
> #523 - после этого пр можно мержить

мне надо было зависимости обновить (next не было)

@Malcom1986 теперь всё норм. Единственное - свои коммиты я делал дней 5-6 назад. В оригинальной репе появились новые коммиты и они ребейзнулись сверху моих. От меня требуется всё переделывать или нет?

2022-10-27 15:12 UTC, dzencot commented
@evgeniyworkbel конфликтов нет, так что всё ок, можно мержить.

2022-10-27 19:08 UTC, merged