[#542]Add micrometric for articles
Hexlet/hexletguides.github.io pull request #550
Opened 2022-11-28 14:37 UTC by HunterGan

Добавил компонент <Micrometric />. Поскольку разметка может добавляться как в Head так и в Body, добавил в body, чтобы генерация была только в отвечающих за посты компонентах без добавления лишней логики.

2022-11-29 06:10 UTC, acidmaksim commented
@dzencot Посмотри, пожалуйста

2022-11-29 18:50 UTC, dzencot requested changes

2022-11-29 18:50 UTC, dzencot commented on components/MicrometricArticles.jsx
> +    if (!author) return null;
Сделай плз отступы в 2 пробела

2022-12-04 08:30 UTC, HunterGan commented on components/MicrometricArticles.jsx
> +    if (!author) return null;
@dzencot Посмотри пожалуйста)

2022-12-05 16:17 UTC, merged