fix typos
Hexlet/hexletguides.github.io pull request #563
Opened 2023-01-23 10:02 UTC by andrew-walker91

2023-01-24 06:23 UTC, ashikov requested changes

2023-01-24 06:23 UTC, ashikov commented on data/posts/ru/2021-11-26-http-api.md
> +API бывает не только HTTP. Обычно, такие API встречаются внутри сервиса, для взаимодействия его компонентов, каждый из которых ведет себя как маленький сервис. Такие API могут использовать как другой
@andrew-walker91 тут всё-таки нужен мягкий знак. 
```
API могут ... (что делать?) строиться ... 
```

2023-01-24 07:24 UTC, andrew-walker91 commented on data/posts/ru/2021-11-26-http-api.md
> +API бывает не только HTTP. Обычно, такие API встречаются внутри сервиса, для взаимодействия его компонентов, каждый из которых ведет себя как маленький сервис. Такие API могут использовать как другой
@ashikov сори, я отнес это к протоколу))

2023-01-25 14:16 UTC, andrew-walker91 commented
@ashikov Роман, посмотри пожалуйста

2023-01-25 14:24 UTC, merged